apiVersion: 1

datasources:
  - name: InfluxDB-Governanca
    uid: InfluxDB-Governanca
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: false
    jsonData:
      version: Flux
      organization: grupogadens
      defaultBucket: governanca-m365
      tlsSkipVerify: true
      httpMode: POST
    secureJsonData:
      token: ${INFLUX_TOKEN}
    editable: true
