"""create ativos table

Revision ID: 4a2c8e291c96
Revises:
Create Date: 2026-06-02 12:34:57.702254

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a2c8e291c96"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ativos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nome", sa.String(length=100), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=True),
        sa.Column("tipo", sa.String(length=20), nullable=False),
        sa.Column("ambiente", sa.String(length=10), nullable=False),
        sa.Column("criticidade", sa.String(length=10), nullable=False),
        sa.Column("owner", sa.String(length=255), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("contrato_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ativos_ambiente"), "ativos", ["ambiente"], unique=False)
    op.create_index(op.f("ix_ativos_criticidade"), "ativos", ["criticidade"], unique=False)
    op.create_index("ix_ativos_deleted_at", "ativos", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_ativos_nome"), "ativos", ["nome"], unique=False)
    op.create_index("ix_ativos_nome_tipo", "ativos", ["nome", "tipo"], unique=True)
    op.create_index(op.f("ix_ativos_owner"), "ativos", ["owner"], unique=False)
    op.create_index(op.f("ix_ativos_tipo"), "ativos", ["tipo"], unique=False)
    op.create_index("ix_ativos_tipo_ambiente", "ativos", ["tipo", "ambiente"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ativos_tipo_ambiente", table_name="ativos")
    op.drop_index(op.f("ix_ativos_tipo"), table_name="ativos")
    op.drop_index(op.f("ix_ativos_owner"), table_name="ativos")
    op.drop_index("ix_ativos_nome_tipo", table_name="ativos")
    op.drop_index(op.f("ix_ativos_nome"), table_name="ativos")
    op.drop_index("ix_ativos_deleted_at", table_name="ativos")
    op.drop_index(op.f("ix_ativos_criticidade"), table_name="ativos")
    op.drop_index(op.f("ix_ativos_ambiente"), table_name="ativos")
    op.drop_table("ativos")
    # ### end Alembic commands ###
